In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model


# Dummies variable using pandas

In [3]:
df=pd.read_csv('homepricetown.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

# Reverte town


In [9]:
dumiesdf= pd.get_dummies(df.town)
#dumiesdf[['monroe township']]= dumiesdf['monroe township'].replace({False:0 , True :1})
dumiesdf=dumiesdf.astype(int)
dumiesdf

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [ ]:
#dr0p


In [10]:
#concatinate
merge = pd.concat([df, dumiesdf], axis = 'columns')
merge

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [14]:
final = merge.drop(['town', 'west windsor'], axis = 'columns')
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [15]:
y = final.price

In [16]:
#x=area,town--->price prediction
x=final.drop('price', axis = 'columns')

#if i want to goback to the vinterser 2 zeros =wintswe
#0,0 =wintswe
#0,1 = robinsville 
#1,0 =monroe 
#sqfeet,area,town 

In [22]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [23]:
model.fit(x,y)

LinearRegression()

In [24]:
model.predict(x)

array([539709.7398409 , 590468.71640508, 615848.20468716, 666607.18125134,
       717366.15781551, 579723.71533005, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [25]:
#Accuracy
model.score(x,y)

0.9573929037221872

In [ ]:
#model.predict([[5000, 1, 0]])
#model.predict([[5000, 0, 1]])
#model.predict([[5000, 1, 0]])

# using scikitlearn label coder

In [29]:
#purpose of lbc
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [31]:
#assgined values category on their labels
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [32]:
#values --->  in array formate -->requirment for series process.
x=dfle[['town', 'area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [33]:
y = dfle.price.values
y

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000])

In [34]:
#genrate union values#onehot encoding --->for Dummy  variables.make a catagories of array's for orders purpose -->Here we transform 0,1,2 -->for accuracy purpose
#series data pass
#[0] = position
#remainder = 'passthrough'  ---> existin date k ilwh input dyn
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')


In [35]:
x = ct.fit_transform(x)
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [36]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('town', OneHotEncoder(), [0])])

In [39]:
ct = ColumnTransformer([('area', OneHotEncoder(), [1])], remainder = 'passthrough')

In [40]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('area', OneHotEncoder(), [1])])